# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://githubpsyche.github.io/rememberly/"

git_url = "https://github.com/githubpsyche/rememberly/tree/main/"

def custom_doc_links(name): return None
